title: drumanagh.com
description: If Drumanagh Wilpole exists, this is where you might find him.
remote_theme: drumanagh/daktilo-drumanagh

url: https://drumanagh.com

author:
  fullname: Drumanagh Wilpole
  github: drumanagh
  twitter: wilpole
  tumblr: wilpole
  disqus: drumanagh
